@module sys {
    @constval THIS_IS_A_COMPILE_TIME_CONST_VALUE 0xFFFF
    @constval THIS_IS_A_COMPILE_TIME_CONST_VALUE 0xFFFF
    @constval THIS_IS_A_COMPILE_TIME_CONST_VALUE 0xFFFF
    @constval THIS_IS_A_COMPILE_TIME_CONST_VALUE 0xFFFF
    @constval THIS_IS_A_COMPILE_TIME_CONST_VALUE 0xFFFF
}
